### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by seiler-steinbach** [jtrotsky/vend-image-upload#4]
This is exactly waht i am looking for!

I always get the following error message:

cannot find package "github.com/jtrotsky/govend/vend" in any of:
    /usr/local/go/src/github.com/jtrotsky/govend/vend (from $GOROOT)
    /Users/tonioseiler/work/src/github.com/jtrotsky/govend/vend

**Comment by jtrotsky** [comment]
@seiler-steinbach Hey mate, sorry I never saw this issue. 
Are you still having troubles building?
